/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Alogorithm.Steganograph;
import General.Configuration;
import General.Nimbus;
import WaterMark.AddWaterMark;
import db.Dbcon;
import java.io.File;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.apache.commons.io.FileUtils;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author Jithinpv
 */
public class MessageEncryption extends javax.swing.JFrame {

    public static String encryption_password;
    /**
     * Creates new form Encryption
     */
    ProgressBarThread progressBarThread = new ProgressBarThread();
    long max_data_size = 0;

    ;

    public MessageEncryption() {
        Nimbus.loadLoogAndFeel();
        initComponents();
        this.setLocationRelativeTo(null);
        loadWatermarkTemplates();
        encrypt_button.setEnabled(false);
        Configuration.setIconOnLabel("blue_back_ground.jpg", main_label);
    }
    File masterFile = null;

    public MessageEncryption(String masterFileName) {
        Nimbus.loadLoogAndFeel();
        initComponents();
        this.setLocationRelativeTo(null);
        loadWatermarkTemplates();
        encrypt_button.setEnabled(false);
        masterFile = new File(Configuration.masterPoolLocation + masterFileName);
        max_data_size = Steganograph.getMaxAllowedDataSize(masterFile);
        checkSizeLimit();
        Configuration.setIconOnLabel("blue_back_ground.jpg", main_label);
    }

    private boolean checkSizeLimit() {
        boolean distortion = false;
        long curentLength = secret_message.getText().length();
        long char_left = max_data_size - curentLength;
        if (char_left < 0) {
            distortion = true;
        }
        characters_left_label.setText(char_left + "");

        return distortion;
    }

    private void loadWatermarkTemplates() {
        try {
            ResultSet rs = new Dbcon().select("select * from tbl_water_mark_config where user_id='"+Login.logged_in_user_id+"'");
            while (rs.next()) {
                watermark_templates.addItem(rs.getString("title"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        password_field = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        secret_message = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        encrypt_button = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        watermark_templates = new javax.swing.JComboBox();
        progress_bar = new javax.swing.JProgressBar();
        characters_left_label = new javax.swing.JLabel();
        main_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 45, 110, -1));
        getContentPane().add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 43, 209, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Message");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 91, 110, -1));

        secret_message.setColumns(1);
        secret_message.setLineWrap(true);
        secret_message.setRows(5);
        secret_message.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                secret_messageKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(secret_message);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 91, 209, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Characters left   : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 220, 131, -1));

        jButton1.setText("Add Watermark");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 304, -1, 25));

        encrypt_button.setText("Embed");
        encrypt_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encrypt_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(encrypt_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 304, 81, 25));

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 304, 71, 25));

        getContentPane().add(watermark_templates, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 241, 209, -1));
        getContentPane().add(progress_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 272, 271, 25));

        characters_left_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        characters_left_label.setForeground(new java.awt.Color(255, 255, 255));
        characters_left_label.setText("100");
        getContentPane().add(characters_left_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 220, 72, -1));
        getContentPane().add(main_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 450, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encrypt_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encrypt_buttonActionPerformed
        // TODO add your handling code here:
        String password = new String(password_field.getPassword());
        String message = secret_message.getText();
        if (password.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Enter password");
        } else if (password.length() < 8) {
            JOptionPane.showMessageDialog(rootPane, "Password must be greater than or equal to 8");
        } else if (message.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Enter message");
        } else if (checkSizeLimit()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter secret data less than maximum data size to avoid distortion");
        } else {
            Dbcon dbcon = new Dbcon();
            dbcon.update("update tbl_encryption_log set encryption_start_time='" + System.currentTimeMillis() + "'where process_id='" + EmbedMessage.process_id + "'");
            //dbcon.insert("insert into tbl_encryption_log(encryption_start_time)values('"+System.currentTimeMillis()+"')");
            encryption_password = password;
            File outPutCipherFile = new File(Configuration.masterPoolLocation + FilenameUtils.getBaseName(masterFile.getName()) + "_cipher." + FilenameUtils.getExtension(masterFile.getName()));
            if (Steganograph.embedMessage(masterFile, outPutCipherFile, message, 50, password)) {
                dbcon.update("update tbl_encryption_log set encryption_end_time='" + System.currentTimeMillis() + "' , cipher_file='" + outPutCipherFile.getName() + "' , cipher_file_size='" + outPutCipherFile.length() + "' where process_id='" + EmbedMessage.process_id + "'");
                JOptionPane.showMessageDialog(rootPane, "Successfully embeded data");
                this.dispose();
                SendMessage send = new SendMessage(outPutCipherFile);
                send.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Could not embed, please try again after some time");
            }
        }

    }//GEN-LAST:event_encrypt_buttonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        EmbedMessage embedMessage = new EmbedMessage();
        embedMessage.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private boolean addWaterMark() {
        boolean success = false;
        String waterMarkName = watermark_templates.getSelectedItem().toString();
        ResultSet rs = new Dbcon().select("select * from tbl_water_mark_config where title = '" + waterMarkName + "'");
        try {
            if (rs.next()) {
                String template = rs.getString("template_name");
                String font_family = rs.getString("font_family");
                String font_size = rs.getString("font_size");
                String font_color = rs.getString("font_color");
                String opacityString = rs.getString("opacity");
                float opacity = Float.parseFloat(opacityString);
                opacity = opacity / 100;
                AddWaterMark.addNow(masterFile, font_family, Integer.parseInt(font_size), waterMarkName, opacity, font_color);
                success = true;
            } else {
                JOptionPane.showMessageDialog(rootPane, "Watermark tempalte is corrupted!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return success;
    }

    class ProgressBarThread extends Thread {

        public boolean complete = false;

        public void run() {
            progress_bar.setValue(0);
            int value = 0;
            float chunk = 100;
            while (value <= 100 && !complete) {
                value++;
                try {
                    Thread.sleep(500);
                } catch (Exception e) {
                }
                progress_bar.setValue(100);
            }

        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Dbcon dbcon = new Dbcon();
        dbcon.update("update tbl_encryption_log set water_mark_start_time='" + System.currentTimeMillis() + "' where process_id='" + EmbedMessage.process_id + "'");
        // add water mark now
        progressBarThread.start();
        if (addWaterMark()) {
            dbcon.update("update tbl_encryption_log set water_mark_end_time='" + System.currentTimeMillis() + "' where process_id='" + EmbedMessage.process_id + "'");
            waterMarkComplete();
            encrypt_button.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Adding watermark failed. Please try again later");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

private void secret_messageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secret_messageKeyTyped
    checkSizeLimit();
    // TODO add your handling code here:
}//GEN-LAST:event_secret_messageKeyTyped

    private void waterMarkComplete() {
        progressBarThread.complete = true;
        progress_bar.setValue(100);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessageEncryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessageEncryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessageEncryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessageEncryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MessageEncryption().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel characters_left_label;
    private javax.swing.JButton encrypt_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel main_label;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JProgressBar progress_bar;
    private javax.swing.JTextArea secret_message;
    private javax.swing.JComboBox watermark_templates;
    // End of variables declaration//GEN-END:variables
}
